/**
 * Clase encargada de manejar las fecha y hora reales
 * Versión: 2.0.1 - 16/02/2012
 */
var oNow={meses:['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],dias:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],HUSO:null,t_inicial:null,offsetDate:null,init:function(secfromepoch,offsetinsec){offsetinsec=Math.abs(offsetinsec);oNow.HUSO=offsetinsec/3600;oNow.t_inicial=new Date(1000*secfromepoch);oNow.offsetDate=new Date();},get_fecha:function(showSem){var fecha,ano,mes,dia,diasem;if(typeof showSem==='undefined'){showSem=0;}
fecha=new Date(oNow.t_inicial.getTime()+oNow.offset_now());ano=fecha.getYear();if(ano<200){ano=ano+1900;}
mes=fecha.getMonth();dia=fecha.getDate();diasem=oNow.dias[fecha.getDay()];mes=oNow.meses[mes];if(showSem===1){return diasem+' '+String(dia)+' de '+String(mes)+' de '+String(ano);}else{return String(dia)+' de '+String(mes)+' de '+String(ano);}},get_fecha_min:function(sep){var fecha,ano,mes,dia;if(typeof sep==='undefined'){sep='/';}
fecha=new Date(oNow.t_inicial.getTime()+oNow.offset_now());ano=fecha.getYear();if(ano<200){ano=ano+1900;}
mes=fecha.getMonth();mes=mes+1;dia=fecha.getDate();return oNow.w2(dia,2)+sep+oNow.w2(mes,2)+sep+String(ano);},get_fecha_wday_name:function(){var fecha,diasem;fecha=new Date(oNow.t_inicial.getTime()+oNow.offset_now());diasem=oNow.dias[fecha.getDay()];return diasem;},get_fecha_iso:function(){var fecha,ano,mes,dia,diasem;fecha=new Date(oNow.t_inicial.getTime()+oNow.offset_now());ano=fecha.getYear();if(ano<200){ano=ano+1900;}
mes=fecha.getMonth();dia=fecha.getDate();diasem=oNow.dias[fecha.getDay()];mes=mes+1;return ano+oNow.w2(mes,2)+oNow.w2(dia,2);},get_hora_min:function(){var fecha,fechaGMT,hora,min,seg,strHora;fecha=new Date(oNow.t_inicial.getTime()+oNow.offset_now());fechaGMT=new Date(oNow.t_inicial.getTime()+oNow.offset_now()+oNow.HUSO*3600000);hora=fecha.getHours();min=fecha.getMinutes();seg=fecha.getSeconds();strHora=oNow.w2(hora,2)+':'+oNow.w2(min,2);return strHora;},get_hora:function(){var fecha,fechaGMT,hora,min,seg,strHora;fecha=new Date(oNow.t_inicial.getTime()+oNow.offset_now());fechaGMT=new Date(oNow.t_inicial.getTime()+oNow.offset_now()+oNow.HUSO*3600000);hora=fecha.getHours();min=fecha.getMinutes();seg=fecha.getSeconds();strHora=oNow.w2(hora,2)+':'+oNow.w2(min,2)+':'+oNow.w2(seg,2);return strHora;},get_hora_full:function(){var fecha,fechaGMT,hora,min,seg,horaGMT,minGMT,segGMT,strHora;fecha=new Date(oNow.t_inicial.getTime()+oNow.offset_now());fechaGMT=new Date(oNow.t_inicial.getTime()+oNow.offset_now()+oNow.HUSO*3600000);hora=fecha.getHours();min=fecha.getMinutes();seg=fecha.getSeconds();horaGMT=fechaGMT.getHours();minGMT=fechaGMT.getMinutes();segGMT=fechaGMT.getSeconds();strHora=oNow.w2(hora,2)+':'+oNow.w2(min,2)+':'+oNow.w2(seg,2)+' (GMT '
+oNow.w2(horaGMT,2)+':'+oNow.w2(minGMT,2)+':'+oNow.w2(segGMT,2)+')';return strHora;},offset_now:function(){var ahora=new Date();return ahora.getTime()-oNow.offsetDate.getTime();},w2:function(num,n){num=String(num);while(num.length<n){num='0'+num;}
return num;}};
